name: DOI Registration
on:
  workflow_dispatch:
    inputs:
      blog:
        description: 'Name of the blog'
        type: choice
        options: 
        - I.D.E.A.S
        - Donny Winston
        required: true
      slug:
        description: 'Slug of the blog post'     
        required: true

  # Allows external webhook trigger
  repository_dispatch:
    types:
      - publish
jobs:
  register:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v2          
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Set up Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.4'
      - name: Install briard
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Generate XML
        run: |
          mkdir -p upload
          bundle exec briard https://donnywinston.com/posts/${{ github.event.inputs.slug }} -t crossref > upload/${{ github.event.inputs.slug }}
        env:
          CROSSREF_DEPOSITOR_NAME: ${{ secrets.CROSSREF_DEPOSITOR_NAME }}
          CROSSREF_DEPOSITOR_EMAIL: ${{ secrets.CROSSREF_DEPOSITOR_EMAIL }}
          CROSSREF_REGISTRANT: ${{ secrets.CROSSREF_REGISTRANT }}
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: uploads
          path: upload/${{ github.event.inputs.slug }}         
      - name: Download
        uses: actions/download-artifact@v2
        with:
          name: uploads
      # - name: curl
      #   uses: wei/curl@v1
      #   id: api
      #   with:
      #     args: -X POST -F "operation=doMDUpload" -F "login_id=${{ secrets.CROSSREF_USERNAME_WITH_ROLE }}" -F "login_passwd=${{ secrets.CROSSREF_PASSWORD }}" -F "fname=@upload/${{ github.event.inputs.slug }} https://doi.crossref.org/servlet/deposit
