name: Webhook
on:
  workflow_dispatch:

  # Allows external webhook trigger
  repository_dispatch:
    types:
      - webhook
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7.x'
      - name: Install and run bolognese
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec bolognese -f schema_org -t crossref https://blog.front-matter.io/posts/editorial-by-more-than-200-call-for-emergency-action-to-limit-global-temperature-increases-restore-biodiversity-and-protect-health
  
