name: DOI Registration Front Matter
on:
  workflow_dispatch:
  schedule: 
    - cron: '0 16 * * 1-5'
jobs:
  register:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      CROSSREF_DEPOSITOR_NAME: ${{ secrets.CROSSREF_DEPOSITOR_NAME }}
      CROSSREF_DEPOSITOR_EMAIL: ${{ secrets.CROSSREF_DEPOSITOR_EMAIL }}
      CROSSREF_REGISTRANT: ${{ secrets.CROSSREF_REGISTRANT }}
    steps:
      - uses: actions/checkout@v2          
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Set up Ruby 3.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      - name: Install commonmeta-ruby
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - id: fetch-rss
        uses: FaustVX/GetRSSAction@v3
        with:
          url: "https://blog.front-matter.io/rss/"
          title-regex: "([^\\s]+)"
          xpath-out-selector: "link"
      - name: Generate XML
        run: |
          mkdir -p upload
          bundle exec commonmeta ${{ steps.fetch-rss.outputs.selection }} -t crossref_xml > upload/temp
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: uploads
          path: upload/temp        
      - name: Download
        uses: actions/download-artifact@v2
        with:
          name: uploads
      - name: curl
        uses: wei/curl@v1
        id: api
        with:
          args: -X POST -F "operation=doMDUpload" -F "login_id=${{ secrets.CROSSREF_USERNAME_WITH_ROLE }}" -F "login_passwd=${{ secrets.CROSSREF_PASSWORD }}" -F "fname=@upload/temp https://doi.crossref.org/servlet/deposit
      - name: Notify Slack
        uses: edge/simple-slack-notify@master
        with:
          channel: '#ops'
          color: 'good'
          text: 'A blog post is being updated: ${{ steps.fetch-rss.outputs.selection }}.'
          